### ISSUE TITLE
header in several files are LGPL but refers to file Copying that is BSD-2-Clause

### ISSUE THREAD

**Issue by luisapace** [ruby/racc#134]
Hi, I'm referring to Racc level 1.4.16. 
I've found that several files have this header:

**_You can distribute/modify this program under the terms of
the GNU LGPL, Lesser General Public License version 2.1.
For details of the GNU LGPL, see the file "COPYING"._**

But the file COPYING included in Racc is a BSD-2-Clause.

Could you please clarify if they are remained under LGPL 2.1?

Thanks.

**Comment by hsbt** [comment]
Ruby or BSD-2-Clause are correct license.

https://github.com/ruby/racc/pull/105

I missed to change the license of some of files.

**Comment by luisapace** [comment]
thanks for quick answer.

**Comment by luisapace** [comment]
Hi, I apologize for a new comment: may I kindly ask you to please confirm that this is true for ALL files in the Racc code, inlcuding the following (I give you the entire path in the downloaded gem): 

- racc-1.4.16-0/data.tar.gz/data.tar/fastcache/fastcache.c
- racc-1.4.16-0/data.tar.gz/data.tar/setup.rb
- racc-1.4.16-0/data.tar.gz/data.tar/web/racc.en.rhtml
- racc-1.4.16-0/data.tar.gz/data.tar/web/racc.ja.rhtml

Thanks again.
