### ISSUE TITLE
useless useless feedback

### ISSUE THREAD

**Issue by marcandre** [ruby/racc#137]
```sh
$ racc -l -v -o lib/rubocop/ast/node_pattern/parser.racc.rb lib/rubocop/ast/node_pattern/parser.y 
1 useless nonterminals
2 useless rules
1 shift/reduce conflicts
```

Ok, so I screwed something up. But which useless nonterminals? Which useless rules? And maybe the shift/reduce conflict is hard to express, but still...

**Comment by marcandre** [comment]
Sorry for the noise, just noticed the .output file...

**Comment by zenspider** [comment]
Eh... I think it is still valid critique... Wanna do a PR that at least changes the messaging to say "generate and look at the .output file" ?

**Comment by marcandre** [comment]
Sure...
