### ISSUE TITLE
Parse error on value "..."

### ISSUE THREAD

**Issue by schinery** [ruby/racc#146]
Since upgrading the Brakeman gem to `5.0.0` it's highlighted that `ruby_parse` is failing to parse files that have methods using `...` argument forwarding.

### Background

Racc version: 1.5.2
Rails version: 6.0.3.4
Ruby version: 2.7.2

#### Parse Error

```
Error: path/to/foo.rb:10 :: parse error on value "..." (tDOT3) Could not parse path/to/foo.rb.rb
Location: /Users/me/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
```

Minimal example that does not parse:

```ruby
class Foo
  def do_something(...)
    do_something_else_with_the_same_params(...)
  end

  def do_something_else_with_the_same_params(foo:, bar:)
  end
end
```

**Comment by deepj** [comment]
I have a similar issue with `brakeman 5.0` and `racc` but exactly with pattern matching.

```ruby
case message
in { entity: 'order', operation: 'create' }
  # ...
in { entity: 'user', operation: 'update' }
  # ...
end
```

Error:

```
Error: path/to/file.rb parse error on value ["in", 16] (kIN) Could not parse path/to/file.rb
```

**Comment by schinery** [comment]
Closing as this has been confirmed as a ruby_parser issue here https://github.com/seattlerb/ruby_parser/issues/311#issuecomment-778339341
