### ISSUE TITLE
Spurious initial \n in error messages

### ISSUE THREAD

**Issue by akimd** [ruby/racc#156]
Error messages start with a spurious empty line, as demonstrated by the example below.

```ruby
class ArrayParser

rule

exp   : 'x'
  
---- inner

  def next_token
    ['y', 'y']
  end

---- footer

begin
  ArrayParser.new.do_parse
rescue => e
  puts "error: '#{e}'"
end
```

```
$ racc array.y && ruby array.tab.rb
error: '
parse error on value "y" (error)'
```
It may be connected to some feature I'm unaware of, in which case please point me to the appropriate documentation.

Cheers!

**Comment by zenspider** [comment]
https://github.com/tenderlove/racc/blob/master/lib/racc/parser.rb#L538

tests pass w/o that newline, so I think it should go.
