### ISSUE TITLE
Missing racc 1.6.0 for the java platform (JRuby)

### ISSUE THREAD

**Issue by jsvd** [ruby/racc#172]
Hi friends,

A recent release of racc 1.6.0 without a java platform counterpart is causing rubygems in jruby to pick a gem with native extensions, which will fail to install:

```
❯ jruby -S gem install racc --platform java
Building native extensions. This could take a while...
ERROR:  Error installing racc:
	ERROR: Failed to build gem native extension.

    current directory: /tmp/jruby/jruby-9.2.17.0/lib/ruby/gems/shared/gems/racc-1.6.0/ext/racc/cparse
/tmp/jruby/jruby-9.2.17.0/bin/jruby -I /tmp/jruby/jruby-9.2.17.0/lib/ruby/stdlib -r ./siteconf20211019-58031-9w8bge.rb extconf.rb
checking for rb_block_call()... RuntimeError: The compiler failed to generate an executable file.
You have to install development tools first.
```

~~Maybe it wasn't forgotten and I may be opening this issue too soon (the release was less than 1 hour ago), but since we saw builds fail, I thought to just ask anyway.~~ Y'all forgot! :D

**Comment by hsbt** [comment]
Released java version https://rubygems.org/gems/racc/versions/1.6.0-java now

**Comment by jsvd** [comment]
Thank you @hsbt
