### ISSUE TITLE
Installation on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by JochenLutz** [ruby/racc#185]
> Building native extensions. This could take a while...
> ERROR:  Error installing racc:
>         ERROR: Failed to build gem native extension.
> 
>     current directory: /home/jolutz/.rvm/gems/ruby-3.0.0/gems/racc-1.6.0/ext/racc/cparse
> /home/jolutz/.rvm/rubies/ruby-3.0.0/bin/ruby -I /home/jolutz/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0 -r ./siteconf20220304-1130559-3adf2g.rb extconf.rb
> checking for rb_block_call()... yes
> checking for rb_ary_subseq()... yes
> creating Makefile
> 
> current directory: /home/jolutz/.rvm/gems/ruby-3.0.0/gems/racc-1.6.0/ext/racc/cparse
> make "DESTDIR=" clean
> 
> current directory: /home/jolutz/.rvm/gems/ruby-3.0.0/gems/racc-1.6.0/ext/racc/cparse
> make "DESTDIR="
> compiling cparse.c
> linking shared-object racc/cparse.so
> 
> current directory: /home/jolutz/.rvm/gems/ruby-3.0.0/gems/racc-1.6.0/ext/racc/cparse
> make "DESTDIR=" install
> make: /usr/bin/mkdir: Command not found
> make: *** [Makefile:202: .sitearchdir.-.racc.time] Error 127
> 
> make install failed, exit code 2
> 
> Gem files will remain installed in /home/jolutz/.rvm/gems/ruby-3.0.0/gems/racc-1.6.0 for inspection.
> Results logged to /home/jolutz/.rvm/gems/ruby-3.0.0/extensions/x86_64-linux/3.0.0/racc-1.6.0/gem_make.out

`mkdir` exists in `/bin`.

**Comment by hsbt** [comment]
see https://github.com/ruby/racc/issues/147#issuecomment-828490156
