### ISSUE TITLE
An error occurred while installing racc (1.6.0), and Bundler cannot continue.

### ISSUE THREAD

**Issue by caionakai** [ruby/racc#192]
This error: `An error occurred while installing racc (1.6.0), and Bundler cannot continue.` is happening when I try to update rails from 5.2.8 to 6.0.0 in Alpine 3.13 with Ruby version 2.7.5p203.

Logs from /usr/local/bundle/extensions/x86_64-linux-musl/2.7.0/racc-1.6.0/mkmf.log:
```
"gcc -o conftest -I/usr/local/include/ruby-2.7.0/x86_64-linux-musl -I/usr/local/include/ruby-2.7.0/ruby/backward -I/usr/local/include/ruby-2.7.0 -I.    -g -O2 -fPIC conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

**Comment by olleolleolle** [comment]
Perhaps the Alpine used now does not have ruby-dev package or the like, with the header files needed to build Ruby extensions?

**Comment by hsbt** [comment]
Alpine is not supported by ruby officially.
