### ISSUE TITLE
Embedded parser uses load racc/info

### ISSUE THREAD

**Issue by jwillemsen** [ruby/racc#199]
When using an embedded parser the generated rb uses require racc/info to get `::Racc::VERSION`. As far as I understand it, when using an embedded parser I shouldn't need racc itself anymore, so why include racc/info? 

To reproduce run in the sample directory `racc -o calc.rb -E calc.y` and check the generated calc.rb, see line 23 for the generated require

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/racc/pull/218
