### ISSUE TITLE
Include 9b0a22c999 in release note v1.6.2

### ISSUE THREAD

**Issue by tnir** [ruby/racc#206]
https://github.com/ruby/racc/releases/tag/v1.6.2 misses the largest change https://github.com/ruby/racc/commit/9b0a22c999c3c55ec2aca585468d456d1eca2378 in the release.

**Comment by tnir** [comment]
What do you think? @hsbt

**Comment by hsbt** [comment]
Thanks, I added it to `v1.6.2` release note.

**Comment by tnir** [comment]
Thanks.
