### ISSUE TITLE
v1.7.0 release has v1.6.2 as internal version

### ISSUE THREAD

**Issue by jwillemsen** [ruby/racc#219]
Looks some files need to be updated for a new release, see https://github.com/ruby/racc/commit/8d1c1ed79e2c85ec54b9fb470f7171b34ae3b7e2, these are still not updated for v1.7.0

**Comment by jwillemsen** [comment]
https://github.com/ruby/racc/blob/bf32d32dff14b03cc1d46ad37df7a71d6ee24bb6/ext/racc/cparse/cparse.c#L25

**Comment by hsbt** [comment]
I will update them at next release.

**Comment by hsbt** [comment]
Fixed by https://github.com/ruby/racc/releases/tag/v1.7.1
