### ISSUE TITLE
Correctly document licenses

### ISSUE THREAD

**Issue by headius** [ruby/racc#84]
Currently the only top-level file describing licenses is COPYING, which *only* says that the project is LGPL.

However, parser.rb and the C and Java extensions are licensed under the same terms as Ruby (CRuby/MRI).

The docs at project root should be updated to reflect this.

See jruby/jruby#4603.

**Comment by zenspider** [comment]
Also can be closed? I think everything has been clearly relicensed.

**Comment by hsbt** [comment]
racc-1.5.0 is Ruby license now.
