### ISSUE TITLE
Plan for 1.4.15 or 2.0.0 release?

### ISSUE THREAD

**Issue by seratch** [ruby/racc#91]
I made [a pull request](https://github.com/ruby/ruby/pull/1925) to fix [a typo 'grammer'](https://github.com/ruby/ruby/blob/f945ea86d84f30772f2af5134626e9ca613dd9d7/lib/rdoc/rd/inline_parser.rb#L5) and found that the typo came from racc 1.4.14.

Do you have any plans to release next versions soon?

**Comment by headius** [comment]
cc @zenspider @tenderlove @drbrain

**Comment by headius** [comment]
Pinging again. Maybe there's someone else who could manage this project? I just got bitten by a bug I've already fixed on master.

**Comment by headius** [comment]
Pinging again. I'm working on removing old deprecated code from JRuby (jruby/jruby#6194) and need to know when #92 got into a release (if it did).

**Comment by hsbt** [comment]
FYI: I already released v1.5.0 https://github.com/ruby/racc/releases/tag/v1.5.0

**Comment by zenspider** [comment]
Given v1.5.0, I'm gonna close this. Feel free to reopen if other divergence is found.
